### ISSUE TITLE
Some doc?

### ISSUE THREAD

**Issue by szaghi** [victorsndvg/FPL#8]
Hi Victor,

I am trying to following your work, but it is not so simple. Do you have any plan to add some documentation sources? It could be helpful to have some references.

Anyway, great work! Thank you for sharing it with us!

**Comment by victorsndvg** [comment]
@szaghi ,

I agree with you. Documentation is a must!

Actually I think that the implementation of the kernel code is near to the end. (without error control! it only do what is supposed to do. I'm not sure about the behaviour of the library if the client is not coherent with the datatypes ...)

As soon as possible I will upload more tests, examples and, at least, a basic documentation.

Thank you!

**Comment by szaghi** [comment]
@victorsndvg great!

**Comment by victorsndvg** [comment]
Automatic source code documentation added using Ford. 

You can see it in : http://victorsndvg.github.io/FPL/
